<script setup lang="ts">
import { ref } from 'vue';
const STORAGE_KEY='attendance-help-collapsed';
const collapsed=ref(localStorage.getItem(STORAGE_KEY)==='1');
function toggle(){collapsed.value=!collapsed.value;localStorage.setItem(STORAGE_KEY,collapsed.value?'1':'0')}
const tips=[{icon:'mdi-map-marker-check-outline',title:'Xác minh IP',text:'Chấm công từ mạng công ty khi đơn vị có giới hạn IP.'},{icon:'mdi-wifi',title:'Kết nối Wi-Fi',text:'Dùng Wi-Fi công ty để hệ thống nhận đúng địa chỉ mạng.'},{icon:'mdi-clock-check-outline',title:'Đúng giờ',text:'Chấm trong thời gian ân hạn để tránh ghi nhận đi trễ.'},{icon:'mdi-bell-outline',title:'Thông báo',text:'Theo dõi kết quả nghỉ phép qua kênh thông báo hiện có.'}];
</script>
<template><section class="help-card" :class="{'is-collapsed':collapsed}"><button class="help-heading" type="button" :aria-expanded="!collapsed" @click="toggle"><span><v-icon icon="mdi-lightbulb-outline" size="19"/><strong>Mẹo &amp; hướng dẫn</strong></span><span class="collapse-label">{{collapsed?'Hiện':'Thu gọn'}} <v-icon :icon="collapsed?'mdi-chevron-down':'mdi-chevron-up'" size="18"/></span></button><div v-if="!collapsed" class="tips"><article v-for="tip in tips" :key="tip.title"><span><v-icon :icon="tip.icon" size="20"/></span><div><strong>{{tip.title}}</strong><p>{{tip.text}}</p></div></article></div></section></template>
<style scoped>.help-card{margin-top:12px;border:1px solid var(--smax-grey-200);border-radius:14px;background:#fff;overflow:hidden}.help-heading{width:100%;min-height:48px;display:flex;align-items:center;justify-content:space-between;padding:0 16px;border:0;background:#fff;color:var(--smax-text);cursor:pointer}.help-heading>span{display:flex;align-items:center;gap:8px}.help-heading strong{font-size:13px}.help-heading>span:first-child>.v-icon{color:#bd7410}.collapse-label{color:#7b8190;font-size:10.5px}.tips{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;border-top:1px solid #eff1f4;background:#eff1f4}.tips article{min-height:92px;display:flex;align-items:flex-start;gap:10px;padding:14px;background:#fff}.tips article>span{width:34px;height:34px;flex:0 0 34px;display:grid;place-items:center;border-radius:9px;color:var(--smax-primary);background:var(--smax-primary-soft)}.tips strong{font-size:11.5px;color:#303442}.tips p{margin:3px 0 0;font-size:10.5px;line-height:1.45;color:#858a96}@media(max-width:900px){.tips{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.tips{grid-template-columns:1fr}.help-heading{padding:0 13px}}</style>
